// Auto-generated from outputs/<district>/summary.json + transitions.csv
// by scripts/generate_district_ts.py. DO NOT EDIT BY HAND - rerun the script.

export interface FromClassBreakdown {
  from_label: string;
  area_ha: number;
  pixel_count: number;
}

export interface NearbyFeature {
  name: string;
  type: string;
  distance_km: number;
  source: 'district_context' | 'osm' | string;
}

export interface Transition {
  from_label: string;
  to_label: string;
  pixel_count: number;
  area_ha: number;
}

export interface Hotspot {
  rank: number;
  cord: [number, number]; // [lat, lon]
  score: number;
  area_km2: number;
  bounds_xyxy: [number, number, number, number]; // projected (UTM 45N) bbox
  dominant_from: string;
  dominant_to: string;
  transition_area_ha: number;
  new_built_area_ha: number;
  from_class_breakdown: FromClassBreakdown[];
  settlement_type: 'residential' | 'industrial' | 'mining_adjacent' | 'transport' | 'mixed' | 'unclassified' | string;
  settlement_rationale: string;
  likely_cause: string;
  confidence: number;
  nearby_features: NearbyFeature[];
  narrative: string;
  chip: string; // PNG path
  gif: string;  // GIF path
}

export interface DistrictArtifacts {
  changeHeatmap?: string;
  rgbBeforeAfter?: string;
  transitionMatrix?: string;
  topTransitions?: string;
}

export interface DistrictData {
  district: string;
  year1: number;
  year2: number;
  scheme: string;
  num_hotspots: number;
  total_transition_area_ha: number;
  new_built_total_ha: number;
  settlement_type_breakdown_ha: {
    residential: number;
    industrial: number;
    mining_adjacent: number;
    transport: number;
    mixed: number;
    unclassified: number;
  };
  weights: Record<string, number>;
  hotspots: Hotspot[];
  topTransitions: Transition[];
  artifacts: DistrictArtifacts;
}

export const DISTRICT_DATA: Record<string, DistrictData> = {
  Angul: {
    district: "Angul",
    year1: 2016,
    year2: 2024,
    scheme: "dynamic_world",
    num_hotspots: 5,
    total_transition_area_ha: 91824.84,
    new_built_total_ha: 143.64,
    settlement_type_breakdown_ha: {
      residential: 25.2,
      industrial: 33.84,
      mining_adjacent: 0,
      transport: 33.12,
      mixed: 51.48,
      unclassified: 0,
    },
    weights: {
      ndvi_delta: 0.15,
      ndbi_delta: 0.35,
      landcover_transition: 0.4,
      mndwi_delta: 0,
      nightlights_delta: 0.1,
    },
    hotspots: [
    {
      rank: 1,
      cord: [20.9443, 85.0133],
      score: 713.4147,
      area_km2: 1,
      bounds_xyxy: [292920, 2316760, 293920, 2317760],
      dominant_from: "Trees",
      dominant_to: "Built",
      transition_area_ha: 18.36,
      new_built_area_ha: 20.88,
      from_class_breakdown: [{from_label: "Trees", area_ha: 18.36, pixel_count: 51}, {from_label: "Rangeland", area_ha: 2.52, pixel_count: 7}],
      settlement_type: "mixed",
      settlement_rationale: "mining_adjacent/industrial drivers overlap (MCL Balaram OCP (5.77 km), MCL Hingula OCP (6.79 km); NTPC Talcher Super Thermal (1.27 km))",
      likely_cause: "Forest cleared for urban or industrial development (likely driven by NTPC Talcher Super Thermal, ~1.27 km away)",
      confidence: 0.95,
      nearby_features: [{name: "NTPC Talcher Super Thermal", type: "thermal_power_plant", distance_km: 1.27, source: "district_context"}, {name: "MCL Balaram OCP", type: "coal_mine", distance_km: 5.77, source: "district_context"}, {name: "MCL Hingula OCP", type: "coal_mine", distance_km: 6.79, source: "district_context"}, {name: "MCL Bharatpur OCP", type: "coal_mine", distance_km: 8.06, source: "district_context"}, {name: "MCL Lingaraj OCP", type: "coal_mine", distance_km: 9.55, source: "district_context"}, {name: "(unnamed mine)", type: "mine", distance_km: 1, source: "osm"}, {name: "Hingula-II Coal Mine", type: "mine", distance_km: 2.44, source: "osm"}, {name: "Angul Monnet Power Company Limited", type: "industrial", distance_km: 3.2, source: "osm"}],
      narrative: "Hotspot 1 (20.9443°N, 85.0133°E), 2016→2024. New built-up area: 20.88 ha (18.36 ha from Trees, 2.52 ha from Rangeland). Why: nearest known feature is NTPC Talcher Super Thermal (thermal power plant), ~1.27 km away. District drivers: coal mining, thermal power generation, aluminium smelting. Likely cause: Forest cleared for urban or industrial development (likely driven by NTPC Talcher Super Thermal, ~1.27 km away). Demographic signal: mixed industrial + residential footprint [mining_adjacent/industrial drivers overlap (MCL Balaram OCP (5.77 km), MCL Hingula OCP (6.79 km); NTPC Talcher Super Thermal (1.27 km))]. Confidence: 0.95.",
      chip: "outputs/Angul/chips/hotspot_01.png",
      gif: "outputs/Angul/gifs/hotspot_01.gif",
    },
    {
      rank: 2,
      cord: [20.9188, 85.1579],
      score: 626.1166,
      area_km2: 1,
      bounds_xyxy: [307920, 2313760, 308920, 2314760],
      dominant_from: "Trees",
      dominant_to: "Built",
      transition_area_ha: 22.32,
      new_built_area_ha: 33.84,
      from_class_breakdown: [{from_label: "Trees", area_ha: 22.32, pixel_count: 62}, {from_label: "Rangeland", area_ha: 11.16, pixel_count: 31}, {from_label: "Crops", area_ha: 0.36, pixel_count: 1}],
      settlement_type: "industrial",
      settlement_rationale: "dominated by industrial driver(s): NTPC Kaniha Super Thermal (3.0 km), Talcher Fertilizers Ltd (4.64 km), NTPC Talcher Thermal (7.03 km)",
      likely_cause: "Forest cleared for urban or industrial development (likely driven by NTPC Kaniha Super Thermal, ~3.0 km away)",
      confidence: 0.95,
      nearby_features: [{name: "NTPC Kaniha Super Thermal", type: "thermal_power_plant", distance_km: 3, source: "district_context"}, {name: "Banarpal", type: "urban_center", distance_km: 3.21, source: "district_context"}, {name: "Talcher Fertilizers Ltd", type: "fertiliser_plant", distance_km: 4.64, source: "district_context"}, {name: "MCL Kaniha OCP", type: "coal_mine", distance_km: 6.47, source: "district_context"}, {name: "NTPC Talcher Thermal", type: "thermal_power_plant", distance_km: 7.03, source: "district_context"}, {name: "NALCO Captive Power Plant", type: "thermal_power_plant", distance_km: 7.33, source: "district_context"}, {name: "MCL Bhubaneswari OCP", type: "coal_mine", distance_km: 7.41, source: "district_context"}, {name: "Jindal Power Angul CPP", type: "thermal_power_plant", distance_km: 7.63, source: "district_context"}],
      narrative: "Hotspot 2 (20.9188°N, 85.1579°E), 2016→2024. New built-up area: 33.84 ha (22.32 ha from Trees, 11.16 ha from Rangeland, 0.36 ha from Crops). Why: nearest known feature is NTPC Kaniha Super Thermal (thermal power plant), ~3.0 km away. District drivers: coal mining, thermal power generation, aluminium smelting. Likely cause: Forest cleared for urban or industrial development (likely driven by NTPC Kaniha Super Thermal, ~3.0 km away). Demographic signal: industrial build-out (plant expansion, workforce housing likely) [dominated by industrial driver(s): NTPC Kaniha Super Thermal (3.0 km), Talcher Fertilizers Ltd (4.64 km), NTPC Talcher Thermal (7.03 km)]. Confidence: 0.95.",
      chip: "outputs/Angul/chips/hotspot_02.png",
      gif: "outputs/Angul/gifs/hotspot_02.gif",
    },
    {
      rank: 3,
      cord: [20.7647, 85.1117],
      score: 593.9416,
      area_km2: 1,
      bounds_xyxy: [302920, 2296760, 303920, 2297760],
      dominant_from: "Trees",
      dominant_to: "Built",
      transition_area_ha: 18.72,
      new_built_area_ha: 33.12,
      from_class_breakdown: [{from_label: "Trees", area_ha: 18.72, pixel_count: 52}, {from_label: "Crops", area_ha: 13.68, pixel_count: 38}, {from_label: "Rangeland", area_ha: 0.72, pixel_count: 2}],
      settlement_type: "transport",
      settlement_rationale: "dominated by transport driver(s): Angul railway station (8.46 km), Angul - Narasinghpur Road (2.54 km), Angul - Narasinghpur Road (3.49 km)",
      likely_cause: "Forest cleared for urban or industrial development (nearest known feature: Angul railway station, ~8.46 km)",
      confidence: 0.8,
      nearby_features: [{name: "Angul railway station", type: "railway_station", distance_km: 8.46, source: "district_context"}, {name: "Angul town", type: "urban_center", distance_km: 8.92, source: "district_context"}, {name: "NALCO Angul Smelter", type: "aluminium_smelter", distance_km: 9.74, source: "district_context"}, {name: "Angul - Narasinghpur Road", type: "road", distance_km: 2.54, source: "osm"}, {name: "Angul - Narasinghpur Road", type: "road", distance_km: 3.49, source: "osm"}, {name: "Angul - Narasinghpur Road", type: "road", distance_km: 4.25, source: "osm"}, {name: "Angul Bypass", type: "road", distance_km: 4.39, source: "osm"}, {name: "Angul Bypass", type: "road", distance_km: 4.39, source: "osm"}],
      narrative: "Hotspot 3 (20.7647°N, 85.1117°E), 2016→2024. New built-up area: 33.12 ha (18.72 ha from Trees, 13.68 ha from Crops, 0.72 ha from Rangeland). Why: nearest known feature is Angul railway station (railway station), ~8.46 km away. District drivers: coal mining, thermal power generation, aluminium smelting. Likely cause: Forest cleared for urban or industrial development (nearest known feature: Angul railway station, ~8.46 km). Demographic signal: transport-corridor development (station/road-led commercial growth) [dominated by transport driver(s): Angul railway station (8.46 km), Angul - Narasinghpur Road (2.54 km), Angul - Narasinghpur Road (3.49 km)]. Confidence: 0.80.",
      chip: "outputs/Angul/chips/hotspot_03.png",
      gif: "outputs/Angul/gifs/hotspot_03.gif",
    },
    {
      rank: 4,
      cord: [20.7653, 85.1597],
      score: 579.3864,
      area_km2: 1,
      bounds_xyxy: [307920, 2296760, 308920, 2297760],
      dominant_from: "Rangeland",
      dominant_to: "Built",
      transition_area_ha: 16.2,
      new_built_area_ha: 30.6,
      from_class_breakdown: [{from_label: "Rangeland", area_ha: 16.2, pixel_count: 45}, {from_label: "Trees", area_ha: 13.32, pixel_count: 37}, {from_label: "Crops", area_ha: 1.08, pixel_count: 3}],
      settlement_type: "mixed",
      settlement_rationale: "transport/residential/industrial drivers overlap (Angul - Narasinghpur Road (1.68 km), Angul - Narasinghpur Road (2.46 km); (unnamed urban) (2.97 km), (unnamed urban) (3.14 km))",
      likely_cause: "Urban/industrial expansion onto rangeland (likely driven by NALCO Angul Smelter, ~9.81 km away)",
      confidence: 0.9,
      nearby_features: [{name: "NALCO Angul Smelter", type: "aluminium_smelter", distance_km: 9.81, source: "district_context"}, {name: "Angul - Narasinghpur Road", type: "road", distance_km: 1.68, source: "osm"}, {name: "Angul - Narasinghpur Road", type: "road", distance_km: 2.46, source: "osm"}, {name: "(unnamed urban)", type: "urban", distance_km: 2.97, source: "osm"}, {name: "(unnamed urban)", type: "urban", distance_km: 3.14, source: "osm"}, {name: "Angul - Narasinghpur Road", type: "road", distance_km: 3.58, source: "osm"}, {name: "Angul Bypass", type: "road", distance_km: 3.91, source: "osm"}, {name: "Angul Bypass", type: "road", distance_km: 3.93, source: "osm"}],
      narrative: "Hotspot 4 (20.7653°N, 85.1597°E), 2016→2024. New built-up area: 30.6 ha (16.2 ha from Rangeland, 13.32 ha from Trees, 1.08 ha from Crops). Why: nearest known feature is NALCO Angul Smelter (aluminium smelter), ~9.81 km away. District drivers: coal mining, thermal power generation, aluminium smelting. Likely cause: Urban/industrial expansion onto rangeland (likely driven by NALCO Angul Smelter, ~9.81 km away). Demographic signal: mixed industrial + residential footprint [transport/residential/industrial drivers overlap (Angul - Narasinghpur Road (1.68 km), Angul - Narasinghpur Road (2.46 km); (unnamed urban) (2.97 km), (unnamed urban) (3.14 km))]. Confidence: 0.90.",
      chip: "outputs/Angul/chips/hotspot_04.png",
      gif: "outputs/Angul/gifs/hotspot_04.gif",
    },
    {
      rank: 5,
      cord: [21.0415, 84.8389],
      score: 510.3463,
      area_km2: 1,
      bounds_xyxy: [274920, 2327760, 275920, 2328760],
      dominant_from: "Crops",
      dominant_to: "Built",
      transition_area_ha: 23.04,
      new_built_area_ha: 25.2,
      from_class_breakdown: [{from_label: "Crops", area_ha: 23.04, pixel_count: 64}, {from_label: "Trees", area_ha: 2.16, pixel_count: 6}],
      settlement_type: "residential",
      settlement_rationale: "dominated by residential driver(s): Chhendipada (3.23 km), Chhendipada (5.93 km), (unnamed settlement) (8.09 km)",
      likely_cause: "Urban or industrial expansion onto farmland (likely driven by Chhendipada, ~3.23 km away)",
      confidence: 0.95,
      nearby_features: [{name: "Chhendipada", type: "urban_center", distance_km: 3.23, source: "district_context"}, {name: "Angul - Deogarh Road", type: "road", distance_km: 5.92, source: "osm"}, {name: "Chhendipada", type: "settlement", distance_km: 5.93, source: "osm"}, {name: "Angul - Deogarh Road", type: "road", distance_km: 6.94, source: "osm"}, {name: "(unnamed settlement)", type: "settlement", distance_km: 8.09, source: "osm"}, {name: "(unnamed settlement)", type: "settlement", distance_km: 8.33, source: "osm"}, {name: "(unnamed settlement)", type: "settlement", distance_km: 8.36, source: "osm"}, {name: "(unnamed settlement)", type: "settlement", distance_km: 8.96, source: "osm"}],
      narrative: "Hotspot 5 (21.0415°N, 84.8389°E), 2016→2024. New built-up area: 25.2 ha (23.04 ha from Crops, 2.16 ha from Trees). Why: nearest known feature is Chhendipada (urban center), ~3.23 km away. District drivers: coal mining, thermal power generation, aluminium smelting. Likely cause: Urban or industrial expansion onto farmland (likely driven by Chhendipada, ~3.23 km away). Demographic signal: settlement / peri-urban growth (housing, population inflow) [dominated by residential driver(s): Chhendipada (3.23 km), Chhendipada (5.93 km), (unnamed settlement) (8.09 km)]. Confidence: 0.95.",
      chip: "outputs/Angul/chips/hotspot_05.png",
      gif: "outputs/Angul/gifs/hotspot_05.gif",
    },
    ],
    topTransitions: [
      { from_label: "Trees", to_label: "Rangeland", pixel_count: 53734, area_ha: 19344.24 },
      { from_label: "Crops", to_label: "Rangeland", pixel_count: 50065, area_ha: 18023.4 },
      { from_label: "Rangeland", to_label: "Crops", pixel_count: 45878, area_ha: 16516.08 },
      { from_label: "Rangeland", to_label: "Trees", pixel_count: 34145, area_ha: 12292.2 },
      { from_label: "Trees", to_label: "Crops", pixel_count: 12976, area_ha: 4671.36 },
      { from_label: "Crops", to_label: "Built", pixel_count: 12354, area_ha: 4447.44 },
      { from_label: "Rangeland", to_label: "Built", pixel_count: 9148, area_ha: 3293.28 },
      { from_label: "Crops", to_label: "Trees", pixel_count: 7535, area_ha: 2712.6 },
      { from_label: "Trees", to_label: "Built", pixel_count: 5172, area_ha: 1861.92 },
      { from_label: "Rangeland", to_label: "Water", pixel_count: 3442, area_ha: 1239.12 },
    ],
    artifacts: {
      changeHeatmap: "outputs/Angul/maps/change_heatmap.png",
      rgbBeforeAfter: "outputs/Angul/maps/rgb_before_after.png",
      transitionMatrix: "outputs/Angul/maps/transition_matrix.png",
      topTransitions: "outputs/Angul/maps/top_transitions.png",
    },
  },
  Balangir: {
    district: "Balangir",
    year1: 2016,
    year2: 2024,
    scheme: "dynamic_world",
    num_hotspots: 5,
    total_transition_area_ha: 153288.72,
    new_built_total_ha: 163.8,
    settlement_type_breakdown_ha: {
      residential: 0,
      industrial: 0,
      mining_adjacent: 0,
      transport: 163.8,
      mixed: 0,
      unclassified: 0,
    },
    weights: {
      ndvi_delta: 0.15,
      ndbi_delta: 0.35,
      landcover_transition: 0.4,
      mndwi_delta: 0,
      nightlights_delta: 0.1,
    },
    hotspots: [
    {
      rank: 1,
      cord: [20.7189, 83.4724],
      score: 711.9464,
      area_km2: 1,
      bounds_xyxy: [132020, 2294540, 133020, 2295540],
      dominant_from: "Crops",
      dominant_to: "Built",
      transition_area_ha: 47.16,
      new_built_area_ha: 50.04,
      from_class_breakdown: [{from_label: "Crops", area_ha: 47.16, pixel_count: 131}, {from_label: "Trees", area_ha: 2.52, pixel_count: 7}, {from_label: "Water", area_ha: 0.36, pixel_count: 1}],
      settlement_type: "transport",
      settlement_rationale: "dominated by transport driver(s): Balangir railway station (2.81 km), (unnamed road) (0.54 km), Patnagarh Road (1.29 km)",
      likely_cause: "Urban or industrial expansion onto farmland (likely driven by Balangir town, ~2.03 km away)",
      confidence: 0.95,
      nearby_features: [{name: "Balangir town", type: "urban_center", distance_km: 2.03, source: "district_context"}, {name: "Balangir railway station", type: "railway_station", distance_km: 2.81, source: "district_context"}, {name: "(unnamed road)", type: "road", distance_km: 0.54, source: "osm"}, {name: "Patnagarh Road", type: "road", distance_km: 1.29, source: "osm"}, {name: "Patnagarh Road", type: "road", distance_km: 1.3, source: "osm"}, {name: "(unnamed power_plant)", type: "power_plant", distance_km: 1.59, source: "osm"}, {name: "(unnamed industrial)", type: "industrial", distance_km: 1.59, source: "osm"}, {name: "Rajendra College Road", type: "road", distance_km: 1.61, source: "osm"}],
      narrative: "Hotspot 1 (20.7189°N, 83.4724°E), 2016→2024. New built-up area: 50.04 ha (47.16 ha from Crops, 2.52 ha from Trees, 0.36 ha from Water). Why: nearest known feature is Balangir town (urban center), ~2.03 km away. District drivers: agricultural activity, urban expansion, transport. Likely cause: Urban or industrial expansion onto farmland (likely driven by Balangir town, ~2.03 km away). Demographic signal: transport-corridor development (station/road-led commercial growth) [dominated by transport driver(s): Balangir railway station (2.81 km), (unnamed road) (0.54 km), Patnagarh Road (1.29 km)]. Confidence: 0.95.",
      chip: "outputs/Balangir/chips/hotspot_01.png",
      gif: "outputs/Balangir/gifs/hotspot_01.gif",
    },
    {
      rank: 2,
      cord: [20.4628, 82.9039],
      score: 510.2342,
      area_km2: 1,
      bounds_xyxy: [72020, 2267540, 73020, 2268540],
      dominant_from: "Rangeland",
      dominant_to: "Built",
      transition_area_ha: 32.04,
      new_built_area_ha: 33.48,
      from_class_breakdown: [{from_label: "Rangeland", area_ha: 32.04, pixel_count: 89}, {from_label: "Crops", area_ha: 1.44, pixel_count: 4}],
      settlement_type: "transport",
      settlement_rationale: "dominated by transport driver(s): Kantabanji railway station (3.34 km), Ashram Pada Road (0.87 km), Ashram Pada Road (1.16 km)",
      likely_cause: "Urban/industrial expansion onto rangeland (nearest known feature: Kantabanji railway station, ~3.34 km)",
      confidence: 0.75,
      nearby_features: [{name: "Kantabanji railway station", type: "railway_station", distance_km: 3.34, source: "district_context"}, {name: "Kantabanji", type: "urban_center", distance_km: 3.63, source: "district_context"}, {name: "Ashram Pada Road", type: "road", distance_km: 0.87, source: "osm"}, {name: "Ashram Pada Road", type: "road", distance_km: 1.16, source: "osm"}, {name: "(unnamed railway)", type: "railway", distance_km: 1.23, source: "osm"}, {name: "Kantabanji", type: "railway", distance_km: 1.29, source: "osm"}, {name: "(unnamed railway)", type: "railway", distance_km: 1.32, source: "osm"}, {name: "(unnamed railway)", type: "railway", distance_km: 1.34, source: "osm"}],
      narrative: "Hotspot 2 (20.4628°N, 82.9039°E), 2016→2024. New built-up area: 33.48 ha (32.04 ha from Rangeland, 1.44 ha from Crops). Why: nearest known feature is Kantabanji railway station (railway station), ~3.34 km away. District drivers: agricultural activity, urban expansion, transport. Likely cause: Urban/industrial expansion onto rangeland (nearest known feature: Kantabanji railway station, ~3.34 km). Demographic signal: transport-corridor development (station/road-led commercial growth) [dominated by transport driver(s): Kantabanji railway station (3.34 km), Ashram Pada Road (0.87 km), Ashram Pada Road (1.16 km)]. Confidence: 0.75.",
      chip: "outputs/Balangir/chips/hotspot_02.png",
      gif: "outputs/Balangir/gifs/hotspot_02.gif",
    },
    {
      rank: 3,
      cord: [20.7392, 83.587],
      score: 497.4539,
      area_km2: 1,
      bounds_xyxy: [144020, 2296540, 145020, 2297540],
      dominant_from: "Rangeland",
      dominant_to: "Built",
      transition_area_ha: 26.64,
      new_built_area_ha: 27,
      from_class_breakdown: [{from_label: "Rangeland", area_ha: 26.64, pixel_count: 74}, {from_label: "Water", area_ha: 0.36, pixel_count: 1}],
      settlement_type: "transport",
      settlement_rationale: "dominated by transport driver(s): (unnamed railway) (0.51 km), (unnamed railway) (0.66 km), (unnamed railway) (0.67 km)",
      likely_cause: "Urban/industrial expansion onto rangeland",
      confidence: 0.7,
      nearby_features: [{name: "(unnamed railway)", type: "railway", distance_km: 0.51, source: "osm"}, {name: "(unnamed railway)", type: "railway", distance_km: 0.66, source: "osm"}, {name: "(unnamed railway)", type: "railway", distance_km: 0.67, source: "osm"}, {name: "(unnamed railway)", type: "railway", distance_km: 0.95, source: "osm"}, {name: "(unnamed railway)", type: "railway", distance_km: 1.41, source: "osm"}, {name: "Sonepur Road", type: "road", distance_km: 1.75, source: "osm"}, {name: "(unnamed railway)", type: "railway", distance_km: 1.81, source: "osm"}, {name: "(unnamed railway)", type: "railway", distance_km: 1.92, source: "osm"}],
      narrative: "Hotspot 3 (20.7392°N, 83.5870°E), 2016→2024. New built-up area: 27.0 ha (26.64 ha from Rangeland, 0.36 ha from Water). Why: nearest known feature is (unnamed railway) (railway), ~0.51 km away. District drivers: agricultural activity, urban expansion, transport. Likely cause: Urban/industrial expansion onto rangeland. Demographic signal: transport-corridor development (station/road-led commercial growth) [dominated by transport driver(s): (unnamed railway) (0.51 km), (unnamed railway) (0.66 km), (unnamed railway) (0.67 km)]. Confidence: 0.70.",
      chip: "outputs/Balangir/chips/hotspot_03.png",
      gif: "outputs/Balangir/gifs/hotspot_03.gif",
    },
    {
      rank: 4,
      cord: [20.4634, 82.9326],
      score: 443.6571,
      area_km2: 1,
      bounds_xyxy: [75020, 2267540, 76020, 2268540],
      dominant_from: "Crops",
      dominant_to: "Built",
      transition_area_ha: 24.84,
      new_built_area_ha: 25.56,
      from_class_breakdown: [{from_label: "Crops", area_ha: 24.84, pixel_count: 69}, {from_label: "Trees", area_ha: 0.72, pixel_count: 2}],
      settlement_type: "transport",
      settlement_rationale: "dominated by transport driver(s): Kantabanji railway station (6.25 km), (unnamed road) (1.37 km), Underbridge Road (1.71 km)",
      likely_cause: "Urban or industrial expansion onto farmland (nearest known feature: Kantabanji railway station, ~6.25 km)",
      confidence: 0.8,
      nearby_features: [{name: "Kantabanji railway station", type: "railway_station", distance_km: 6.25, source: "district_context"}, {name: "Kantabanji", type: "urban_center", distance_km: 6.57, source: "district_context"}, {name: "(unnamed road)", type: "road", distance_km: 1.37, source: "osm"}, {name: "Kantabanji", type: "settlement", distance_km: 1.43, source: "osm"}, {name: "Underbridge Road", type: "road", distance_km: 1.71, source: "osm"}, {name: "Main Road", type: "road", distance_km: 1.71, source: "osm"}, {name: "(unnamed railway)", type: "railway", distance_km: 1.72, source: "osm"}, {name: "(unnamed road)", type: "road", distance_km: 1.73, source: "osm"}],
      narrative: "Hotspot 4 (20.4634°N, 82.9326°E), 2016→2024. New built-up area: 25.56 ha (24.84 ha from Crops, 0.72 ha from Trees). Why: nearest known feature is Kantabanji railway station (railway station), ~6.25 km away. District drivers: agricultural activity, urban expansion, transport. Likely cause: Urban or industrial expansion onto farmland (nearest known feature: Kantabanji railway station, ~6.25 km). Demographic signal: transport-corridor development (station/road-led commercial growth) [dominated by transport driver(s): Kantabanji railway station (6.25 km), (unnamed road) (1.37 km), Underbridge Road (1.71 km)]. Confidence: 0.80.",
      chip: "outputs/Balangir/chips/hotspot_04.png",
      gif: "outputs/Balangir/gifs/hotspot_04.gif",
    },
    {
      rank: 5,
      cord: [20.711, 83.5301],
      score: 442.9648,
      area_km2: 1,
      bounds_xyxy: [138020, 2293540, 139020, 2294540],
      dominant_from: "Rangeland",
      dominant_to: "Built",
      transition_area_ha: 19.44,
      new_built_area_ha: 27.72,
      from_class_breakdown: [{from_label: "Rangeland", area_ha: 19.44, pixel_count: 54}, {from_label: "Crops", area_ha: 8.28, pixel_count: 23}],
      settlement_type: "transport",
      settlement_rationale: "dominated by transport driver(s): Balangir railway station (3.71 km), (unnamed railway) (0.26 km), (unnamed railway) (0.93 km)",
      likely_cause: "Urban/industrial expansion onto rangeland (nearest known feature: Balangir railway station, ~3.71 km)",
      confidence: 0.75,
      nearby_features: [{name: "Balangir railway station", type: "railway_station", distance_km: 3.71, source: "district_context"}, {name: "Balangir town", type: "urban_center", distance_km: 4.74, source: "district_context"}, {name: "(unnamed railway)", type: "railway", distance_km: 0.26, source: "osm"}, {name: "(unnamed railway)", type: "railway", distance_km: 0.93, source: "osm"}, {name: "(unnamed railway)", type: "railway", distance_km: 1.04, source: "osm"}, {name: "(unnamed railway)", type: "railway", distance_km: 1.97, source: "osm"}, {name: "(unnamed railway)", type: "railway", distance_km: 1.97, source: "osm"}, {name: "(unnamed railway)", type: "railway", distance_km: 2.68, source: "osm"}],
      narrative: "Hotspot 5 (20.7110°N, 83.5301°E), 2016→2024. New built-up area: 27.72 ha (19.44 ha from Rangeland, 8.28 ha from Crops). Why: nearest known feature is Balangir railway station (railway station), ~3.71 km away. District drivers: agricultural activity, urban expansion, transport. Likely cause: Urban/industrial expansion onto rangeland (nearest known feature: Balangir railway station, ~3.71 km). Demographic signal: transport-corridor development (station/road-led commercial growth) [dominated by transport driver(s): Balangir railway station (3.71 km), (unnamed railway) (0.26 km), (unnamed railway) (0.93 km)]. Confidence: 0.75.",
      chip: "outputs/Balangir/chips/hotspot_05.png",
      gif: "outputs/Balangir/gifs/hotspot_05.gif",
    },
    ],
    topTransitions: [
      { from_label: "Rangeland", to_label: "Crops", pixel_count: 140957, area_ha: 50744.52 },
      { from_label: "Trees", to_label: "Rangeland", pixel_count: 118782, area_ha: 42761.52 },
      { from_label: "Crops", to_label: "Rangeland", pixel_count: 59768, area_ha: 21516.48 },
      { from_label: "Trees", to_label: "Crops", pixel_count: 47434, area_ha: 17076.24 },
      { from_label: "Crops", to_label: "Built", pixel_count: 14400, area_ha: 5184 },
      { from_label: "Rangeland", to_label: "Trees", pixel_count: 11729, area_ha: 4222.44 },
      { from_label: "Rangeland", to_label: "Built", pixel_count: 7363, area_ha: 2650.68 },
      { from_label: "Crops", to_label: "Trees", pixel_count: 4913, area_ha: 1768.68 },
      { from_label: "Built", to_label: "Crops", pixel_count: 3105, area_ha: 1117.8 },
      { from_label: "Trees", to_label: "Built", pixel_count: 2988, area_ha: 1075.68 },
    ],
    artifacts: {
      changeHeatmap: "outputs/Balangir/maps/change_heatmap.png",
      rgbBeforeAfter: "outputs/Balangir/maps/rgb_before_after.png",
      transitionMatrix: "outputs/Balangir/maps/transition_matrix.png",
      topTransitions: "outputs/Balangir/maps/top_transitions.png",
    },
  },
  Cuttack: {
    district: "Cuttack",
    year1: 2016,
    year2: 2024,
    scheme: "dynamic_world",
    num_hotspots: 5,
    total_transition_area_ha: 54784.08,
    new_built_total_ha: 162.36,
    settlement_type_breakdown_ha: {
      residential: 53.28,
      industrial: 0,
      mining_adjacent: 0,
      transport: 109.08,
      mixed: 0,
      unclassified: 0,
    },
    weights: {
      ndvi_delta: 0.15,
      ndbi_delta: 0.35,
      landcover_transition: 0.4,
      mndwi_delta: 0,
      nightlights_delta: 0.1,
    },
    hotspots: [
    {
      rank: 1,
      cord: [20.4964, 86.0485],
      score: 780.896,
      area_km2: 1,
      bounds_xyxy: [400280, 2266200, 401280, 2267200],
      dominant_from: "Trees",
      dominant_to: "Built",
      transition_area_ha: 38.52,
      new_built_area_ha: 46.44,
      from_class_breakdown: [{from_label: "Trees", area_ha: 38.52, pixel_count: 107}, {from_label: "Crops", area_ha: 7.92, pixel_count: 22}],
      settlement_type: "transport",
      settlement_rationale: "dominated by transport driver(s): (unnamed road) (1.71 km), (unnamed road) (2.66 km), (unnamed road) (3.36 km)",
      likely_cause: "Forest cleared for urban or industrial development (likely driven by Salipur, ~9.06 km away)",
      confidence: 0.95,
      nearby_features: [{name: "Salipur", type: "urban_center", distance_km: 9.06, source: "district_context"}, {name: "(unnamed road)", type: "road", distance_km: 1.71, source: "osm"}, {name: "(unnamed road)", type: "road", distance_km: 2.66, source: "osm"}, {name: "(unnamed road)", type: "road", distance_km: 3.36, source: "osm"}, {name: "(unnamed road)", type: "road", distance_km: 3.98, source: "osm"}, {name: "(unnamed road)", type: "road", distance_km: 4.15, source: "osm"}, {name: "(unnamed road)", type: "road", distance_km: 6.05, source: "osm"}, {name: "Salepur", type: "settlement", distance_km: 6.16, source: "osm"}],
      narrative: "Hotspot 1 (20.4964°N, 86.0485°E), 2016→2024. New built-up area: 46.44 ha (38.52 ha from Trees, 7.92 ha from Crops). Why: nearest known feature is Salipur (urban center), ~9.06 km away. District drivers: urban expansion, industrial, port logistics. Likely cause: Forest cleared for urban or industrial development (likely driven by Salipur, ~9.06 km away). Demographic signal: transport-corridor development (station/road-led commercial growth) [dominated by transport driver(s): (unnamed road) (1.71 km), (unnamed road) (2.66 km), (unnamed road) (3.36 km)]. Confidence: 0.95.",
      chip: "outputs/Cuttack/chips/hotspot_01.png",
      gif: "outputs/Cuttack/gifs/hotspot_01.gif",
    },
    {
      rank: 2,
      cord: [20.4405, 85.7805],
      score: 768.2241,
      area_km2: 1,
      bounds_xyxy: [372280, 2260200, 373280, 2261200],
      dominant_from: "Crops",
      dominant_to: "Built",
      transition_area_ha: 31.32,
      new_built_area_ha: 62.64,
      from_class_breakdown: [{from_label: "Crops", area_ha: 31.32, pixel_count: 87}, {from_label: "Rangeland", area_ha: 26.64, pixel_count: 74}, {from_label: "Trees", area_ha: 4.68, pixel_count: 13}],
      settlement_type: "transport",
      settlement_rationale: "dominated by transport driver(s): Cuttack railway station (9.77 km), (unnamed road) (1.45 km), (unnamed road) (1.83 km)",
      likely_cause: "Urban or industrial expansion onto farmland (nearest known feature: Cuttack railway station, ~9.77 km)",
      confidence: 0.8,
      nearby_features: [{name: "Cuttack railway station", type: "railway_station", distance_km: 9.77, source: "district_context"}, {name: "(unnamed road)", type: "road", distance_km: 1.45, source: "osm"}, {name: "(unnamed road)", type: "road", distance_km: 1.83, source: "osm"}, {name: "(unnamed railway)", type: "railway", distance_km: 2.04, source: "osm"}, {name: "(unnamed railway)", type: "railway", distance_km: 2.04, source: "osm"}, {name: "(unnamed railway)", type: "railway", distance_km: 2.04, source: "osm"}, {name: "(unnamed railway)", type: "railway", distance_km: 2.05, source: "osm"}, {name: "(unnamed railway)", type: "railway", distance_km: 2.05, source: "osm"}],
      narrative: "Hotspot 2 (20.4405°N, 85.7805°E), 2016→2024. New built-up area: 62.64 ha (31.32 ha from Crops, 26.64 ha from Rangeland, 4.68 ha from Trees). Why: nearest known feature is Cuttack railway station (railway station), ~9.77 km away. District drivers: urban expansion, industrial, port logistics. Likely cause: Urban or industrial expansion onto farmland (nearest known feature: Cuttack railway station, ~9.77 km). Demographic signal: transport-corridor development (station/road-led commercial growth) [dominated by transport driver(s): Cuttack railway station (9.77 km), (unnamed road) (1.45 km), (unnamed road) (1.83 km)]. Confidence: 0.80.",
      chip: "outputs/Cuttack/chips/hotspot_02.png",
      gif: "outputs/Cuttack/gifs/hotspot_02.gif",
    },
    {
      rank: 3,
      cord: [20.5149, 86.1443],
      score: 677.3582,
      area_km2: 1,
      bounds_xyxy: [410280, 2268200, 411280, 2269200],
      dominant_from: "Trees",
      dominant_to: "Built",
      transition_area_ha: 46.8,
      new_built_area_ha: 53.28,
      from_class_breakdown: [{from_label: "Trees", area_ha: 46.8, pixel_count: 130}, {from_label: "Crops", area_ha: 6.48, pixel_count: 18}],
      settlement_type: "residential",
      settlement_rationale: "dominated by residential driver(s): Salipur (6.32 km), Salepur (5.78 km), Mahanga (5.8 km)",
      likely_cause: "Forest cleared for urban or industrial development (likely driven by Salipur, ~6.32 km away)",
      confidence: 0.95,
      nearby_features: [{name: "Salipur", type: "urban_center", distance_km: 6.32, source: "district_context"}, {name: "(unnamed road)", type: "road", distance_km: 4.77, source: "osm"}, {name: "(unnamed power_plant)", type: "power_plant", distance_km: 5.47, source: "osm"}, {name: "Salepur", type: "settlement", distance_km: 5.78, source: "osm"}, {name: "Mahanga", type: "settlement", distance_km: 5.8, source: "osm"}, {name: "Nischintakoili", type: "settlement", distance_km: 5.82, source: "osm"}, {name: "(unnamed road)", type: "road", distance_km: 5.85, source: "osm"}, {name: "Luna", type: "river", distance_km: 6.43, source: "osm"}],
      narrative: "Hotspot 3 (20.5149°N, 86.1443°E), 2016→2024. New built-up area: 53.28 ha (46.8 ha from Trees, 6.48 ha from Crops). Why: nearest known feature is Salipur (urban center), ~6.32 km away. District drivers: urban expansion, industrial, port logistics. Likely cause: Forest cleared for urban or industrial development (likely driven by Salipur, ~6.32 km away). Demographic signal: settlement / peri-urban growth (housing, population inflow) [dominated by residential driver(s): Salipur (6.32 km), Salepur (5.78 km), Mahanga (5.8 km)]. Confidence: 0.95.",
      chip: "outputs/Cuttack/chips/hotspot_03.png",
      gif: "outputs/Cuttack/gifs/hotspot_03.gif",
    },
    {
      rank: 4,
      cord: [20.5879, 85.0982],
      score: 648.1877,
      area_km2: 1,
      bounds_xyxy: [301280, 2277200, 302280, 2278200],
      dominant_from: "unchanged",
      dominant_to: "unchanged",
      transition_area_ha: 0,
      new_built_area_ha: 0,
      from_class_breakdown: [],
      settlement_type: "mixed",
      settlement_rationale: "residential/transport drivers overlap (Bhurukund (8.39 km), Hindol (10.68 km); Angul - Narasinghpur Road (5.73 km), Angul - Narasinghpur Road (10.51 km))",
      likely_cause: "Unclassified land-cover change",
      confidence: 0.3,
      nearby_features: [{name: "Angul - Narasinghpur Road", type: "road", distance_km: 5.73, source: "osm"}, {name: "Bhurukund", type: "settlement", distance_km: 8.39, source: "osm"}, {name: "Angul - Narasinghpur Road", type: "road", distance_km: 10.51, source: "osm"}, {name: "Hindol", type: "urban", distance_km: 10.68, source: "osm"}, {name: "Kanagudi", type: "settlement", distance_km: 12.78, source: "osm"}, {name: "Kamaladih Narasinghpur Road", type: "road", distance_km: 15.28, source: "osm"}],
      narrative: "Hotspot 4 (20.5879°N, 85.0982°E), 2016→2024. No net new built-up inside hotspot; dominant change: unchanged → unchanged (0.0 ha). Why: nearest known feature is Angul - Narasinghpur Road (road), ~5.73 km away. District drivers: urban expansion, industrial, port logistics. Likely cause: Unclassified land-cover change. Demographic signal: mixed industrial + residential footprint [residential/transport drivers overlap (Bhurukund (8.39 km), Hindol (10.68 km); Angul - Narasinghpur Road (5.73 km), Angul - Narasinghpur Road (10.51 km))]. Confidence: 0.30.",
      chip: "outputs/Cuttack/chips/hotspot_04.png",
      gif: "outputs/Cuttack/gifs/hotspot_04.gif",
    },
    {
      rank: 5,
      cord: [20.4959, 85.9718],
      score: 631.616,
      area_km2: 1,
      bounds_xyxy: [392280, 2266200, 393280, 2267200],
      dominant_from: "Trees",
      dominant_to: "Built",
      transition_area_ha: 25.56,
      new_built_area_ha: 0,
      from_class_breakdown: [],
      settlement_type: "transport",
      settlement_rationale: "dominated by transport driver(s): (unnamed road) (0.27 km)",
      likely_cause: "Forest cleared for urban or industrial development (likely driven by Choudwar Industrial Area, ~8.54 km away)",
      confidence: 0.95,
      nearby_features: [{name: "Choudwar Industrial Area", type: "industrial", distance_km: 8.54, source: "district_context"}, {name: "Choudwar", type: "urban_center", distance_km: 9.38, source: "district_context"}, {name: "SAIL Kalinga Nagar (approach)", type: "steel_plant", distance_km: 9.59, source: "district_context"}, {name: "Cuttack city", type: "urban_center", distance_km: 9.99, source: "district_context"}, {name: "(unnamed road)", type: "road", distance_km: 0.27, source: "osm"}, {name: "Pasupati Agrovet Pvt Ltd, Plant 1", type: "industrial", distance_km: 3, source: "osm"}, {name: "(unnamed road)", type: "road", distance_km: 3.05, source: "osm"}, {name: "(unnamed road)", type: "road", distance_km: 3.05, source: "osm"}],
      narrative: "Hotspot 5 (20.4959°N, 85.9718°E), 2016→2024. No net new built-up inside hotspot; dominant change: Trees → Built (25.6 ha). Why: nearest known feature is Choudwar Industrial Area (industrial), ~8.54 km away. District drivers: urban expansion, industrial, port logistics. Likely cause: Forest cleared for urban or industrial development (likely driven by Choudwar Industrial Area, ~8.54 km away). Demographic signal: transport-corridor development (station/road-led commercial growth) [dominated by transport driver(s): (unnamed road) (0.27 km)]. Confidence: 0.95.",
      chip: "outputs/Cuttack/chips/hotspot_05.png",
      gif: "outputs/Cuttack/gifs/hotspot_05.gif",
    },
    ],
    topTransitions: [
      { from_label: "Trees", to_label: "Built", pixel_count: 22679, area_ha: 8164.44 },
      { from_label: "Crops", to_label: "Built", pixel_count: 21674, area_ha: 7802.64 },
      { from_label: "Crops", to_label: "Rangeland", pixel_count: 17946, area_ha: 6460.56 },
      { from_label: "Bare", to_label: "Water", pixel_count: 10341, area_ha: 3722.76 },
      { from_label: "Bare", to_label: "Rangeland", pixel_count: 10226, area_ha: 3681.36 },
      { from_label: "Trees", to_label: "Crops", pixel_count: 9291, area_ha: 3344.76 },
      { from_label: "Rangeland", to_label: "Trees", pixel_count: 9078, area_ha: 3268.08 },
      { from_label: "Rangeland", to_label: "Crops", pixel_count: 8668, area_ha: 3120.48 },
      { from_label: "Crops", to_label: "Trees", pixel_count: 8633, area_ha: 3107.88 },
      { from_label: "Water", to_label: "Bare", pixel_count: 6781, area_ha: 2441.16 },
    ],
    artifacts: {
      changeHeatmap: "outputs/Cuttack/maps/change_heatmap.png",
      rgbBeforeAfter: "outputs/Cuttack/maps/rgb_before_after.png",
      transitionMatrix: "outputs/Cuttack/maps/transition_matrix.png",
      topTransitions: "outputs/Cuttack/maps/top_transitions.png",
    },
  },
  Kendujhar: {
    district: "Kendujhar",
    year1: 2016,
    year2: 2024,
    scheme: "dynamic_world",
    num_hotspots: 5,
    total_transition_area_ha: 113536.8,
    new_built_total_ha: 46.44,
    settlement_type_breakdown_ha: {
      residential: 0,
      industrial: 0,
      mining_adjacent: 0,
      transport: 0,
      mixed: 46.44,
      unclassified: 0,
    },
    weights: {
      ndvi_delta: 0.15,
      ndbi_delta: 0.35,
      landcover_transition: 0.4,
      mndwi_delta: 0,
      nightlights_delta: 0.1,
    },
    hotspots: [
    {
      rank: 1,
      cord: [21.875, 85.4255],
      score: 860.0918,
      area_km2: 1,
      bounds_xyxy: [336820, 2419320, 337820, 2420320],
      dominant_from: "Rangeland",
      dominant_to: "Built",
      transition_area_ha: 33.84,
      new_built_area_ha: 46.44,
      from_class_breakdown: [{from_label: "Rangeland", area_ha: 33.84, pixel_count: 94}, {from_label: "Trees", area_ha: 10.8, pixel_count: 30}, {from_label: "Crops", area_ha: 1.8, pixel_count: 5}],
      settlement_type: "mixed",
      settlement_rationale: "no registered driver nearby; Rangeland→Built transition could be rural settlement or industrial expansion",
      likely_cause: "Urban/industrial expansion onto rangeland",
      confidence: 0.7,
      nearby_features: [],
      narrative: "Hotspot 1 (21.8750°N, 85.4255°E), 2016→2024. New built-up area: 46.44 ha (33.84 ha from Rangeland, 10.8 ha from Trees, 1.8 ha from Crops). Why: no specific nearby feature registered; district drivers are iron-ore mining, manganese, urban expansion. Likely cause: Urban/industrial expansion onto rangeland. Demographic signal: mixed industrial + residential footprint [no registered driver nearby; Rangeland→Built transition could be rural settlement or industrial expansion]. Confidence: 0.70.",
      chip: "outputs/Kendujhar/chips/hotspot_01.png",
      gif: "outputs/Kendujhar/gifs/hotspot_01.gif",
    },
    {
      rank: 2,
      cord: [21.9559, 85.3859],
      score: 821.0828,
      area_km2: 1,
      bounds_xyxy: [332820, 2428320, 333820, 2429320],
      dominant_from: "Trees",
      dominant_to: "Rangeland",
      transition_area_ha: 27,
      new_built_area_ha: 0,
      from_class_breakdown: [],
      settlement_type: "mixed",
      settlement_rationale: "mining_adjacent/transport drivers overlap (Thakurani iron-ore mine (6.14 km); Banspani railway junction (8.96 km))",
      likely_cause: "Forest degradation to open rangeland (nearest known feature: Thakurani iron-ore mine, ~6.14 km)",
      confidence: 0.65,
      nearby_features: [{name: "Thakurani iron-ore mine", type: "iron_ore_mine", distance_km: 6.14, source: "district_context"}, {name: "Banspani railway junction", type: "railway_station", distance_km: 8.96, source: "district_context"}],
      narrative: "Hotspot 2 (21.9559°N, 85.3859°E), 2016→2024. No net new built-up inside hotspot; dominant change: Trees → Rangeland (27.0 ha). Why: nearest known feature is Thakurani iron-ore mine (iron ore mine), ~6.14 km away. District drivers: iron-ore mining, manganese, urban expansion. Likely cause: Forest degradation to open rangeland (nearest known feature: Thakurani iron-ore mine, ~6.14 km). Demographic signal: mixed industrial + residential footprint [mining_adjacent/transport drivers overlap (Thakurani iron-ore mine (6.14 km); Banspani railway junction (8.96 km))]. Confidence: 0.65.",
      chip: "outputs/Kendujhar/chips/hotspot_02.png",
      gif: "outputs/Kendujhar/gifs/hotspot_02.gif",
    },
    {
      rank: 3,
      cord: [22.119, 85.4422],
      score: 736.4583,
      area_km2: 1,
      bounds_xyxy: [338820, 2446320, 339820, 2447320],
      dominant_from: "Trees",
      dominant_to: "Rangeland",
      transition_area_ha: 4.68,
      new_built_area_ha: 0,
      from_class_breakdown: [],
      settlement_type: "residential",
      settlement_rationale: "dominated by residential driver(s): Barbil (6.69 km), Joda (9.06 km)",
      likely_cause: "Forest degradation to open rangeland (nearest known feature: Barbil, ~6.69 km)",
      confidence: 0.65,
      nearby_features: [{name: "Barbil", type: "urban_center", distance_km: 6.69, source: "district_context"}, {name: "Joda-Barbil iron-ore cluster", type: "iron_ore_mine", distance_km: 6.97, source: "district_context"}, {name: "Joda", type: "urban_center", distance_km: 9.06, source: "district_context"}],
      narrative: "Hotspot 3 (22.1190°N, 85.4422°E), 2016→2024. No net new built-up inside hotspot; dominant change: Trees → Rangeland (4.7 ha). Why: nearest known feature is Barbil (urban center), ~6.69 km away. District drivers: iron-ore mining, manganese, urban expansion. Likely cause: Forest degradation to open rangeland (nearest known feature: Barbil, ~6.69 km). Demographic signal: settlement / peri-urban growth (housing, population inflow) [dominated by residential driver(s): Barbil (6.69 km), Joda (9.06 km)]. Confidence: 0.65.",
      chip: "outputs/Kendujhar/chips/hotspot_03.png",
      gif: "outputs/Kendujhar/gifs/hotspot_03.gif",
    },
    {
      rank: 4,
      cord: [22.1178, 85.3259],
      score: 706.3969,
      area_km2: 1,
      bounds_xyxy: [326820, 2446320, 327820, 2447320],
      dominant_from: "Rangeland",
      dominant_to: "Trees",
      transition_area_ha: 4.32,
      new_built_area_ha: 0,
      from_class_breakdown: [],
      settlement_type: "residential",
      settlement_rationale: "dominated by residential driver(s): Barbil (5.86 km)",
      likely_cause: "Unclassified land-cover change (nearest known feature: Barbil, ~5.86 km)",
      confidence: 0.35,
      nearby_features: [{name: "Barbil", type: "urban_center", distance_km: 5.86, source: "district_context"}, {name: "Joda-Barbil iron-ore cluster", type: "iron_ore_mine", distance_km: 9.31, source: "district_context"}],
      narrative: "Hotspot 4 (22.1178°N, 85.3259°E), 2016→2024. No net new built-up inside hotspot; dominant change: Rangeland → Trees (4.3 ha). Why: nearest known feature is Barbil (urban center), ~5.86 km away. District drivers: iron-ore mining, manganese, urban expansion. Likely cause: Unclassified land-cover change (nearest known feature: Barbil, ~5.86 km). Demographic signal: settlement / peri-urban growth (housing, population inflow) [dominated by residential driver(s): Barbil (5.86 km)]. Confidence: 0.35.",
      chip: "outputs/Kendujhar/chips/hotspot_04.png",
      gif: "outputs/Kendujhar/gifs/hotspot_04.gif",
    },
    {
      rank: 5,
      cord: [22.0825, 85.4038],
      score: 689.5088,
      area_km2: 1,
      bounds_xyxy: [334820, 2442320, 335820, 2443320],
      dominant_from: "Rangeland",
      dominant_to: "Trees",
      transition_area_ha: 0.72,
      new_built_area_ha: 0,
      from_class_breakdown: [],
      settlement_type: "mixed",
      settlement_rationale: "mining_adjacent/residential/transport drivers overlap (Joda-Barbil iron-ore cluster (1.44 km); Barbil (3.25 km), Joda (5.35 km))",
      likely_cause: "Unclassified land-cover change (nearest known feature: Joda-Barbil iron-ore cluster, ~1.44 km)",
      confidence: 0.35,
      nearby_features: [{name: "Joda-Barbil iron-ore cluster", type: "iron_ore_mine", distance_km: 1.44, source: "district_context"}, {name: "Barbil", type: "urban_center", distance_km: 3.25, source: "district_context"}, {name: "Joda", type: "urban_center", distance_km: 5.35, source: "district_context"}, {name: "Banspani railway junction", type: "railway_station", distance_km: 6.07, source: "district_context"}],
      narrative: "Hotspot 5 (22.0825°N, 85.4038°E), 2016→2024. No net new built-up inside hotspot; dominant change: Rangeland → Trees (0.7 ha). Why: nearest known feature is Joda-Barbil iron-ore cluster (iron ore mine), ~1.44 km away. District drivers: iron-ore mining, manganese, urban expansion. Likely cause: Unclassified land-cover change (nearest known feature: Joda-Barbil iron-ore cluster, ~1.44 km). Demographic signal: mixed industrial + residential footprint [mining_adjacent/residential/transport drivers overlap (Joda-Barbil iron-ore cluster (1.44 km); Barbil (3.25 km), Joda (5.35 km))]. Confidence: 0.35.",
      chip: "outputs/Kendujhar/chips/hotspot_05.png",
      gif: "outputs/Kendujhar/gifs/hotspot_05.gif",
    },
    ],
    topTransitions: [
      { from_label: "Rangeland", to_label: "Crops", pixel_count: 72399, area_ha: 26063.64 },
      { from_label: "Trees", to_label: "Rangeland", pixel_count: 57142, area_ha: 20571.12 },
      { from_label: "Rangeland", to_label: "Trees", pixel_count: 55241, area_ha: 19886.76 },
      { from_label: "Crops", to_label: "Rangeland", pixel_count: 46208, area_ha: 16634.88 },
      { from_label: "Crops", to_label: "Built", pixel_count: 19885, area_ha: 7158.6 },
      { from_label: "Crops", to_label: "Trees", pixel_count: 13940, area_ha: 5018.4 },
      { from_label: "Rangeland", to_label: "Built", pixel_count: 12366, area_ha: 4451.76 },
      { from_label: "Trees", to_label: "Crops", pixel_count: 12106, area_ha: 4358.16 },
      { from_label: "Trees", to_label: "Built", pixel_count: 6787, area_ha: 2443.32 },
      { from_label: "Built", to_label: "Crops", pixel_count: 4678, area_ha: 1684.08 },
    ],
    artifacts: {
      changeHeatmap: "outputs/Kendujhar/maps/change_heatmap.png",
      rgbBeforeAfter: "outputs/Kendujhar/maps/rgb_before_after.png",
      transitionMatrix: "outputs/Kendujhar/maps/transition_matrix.png",
      topTransitions: "outputs/Kendujhar/maps/top_transitions.png",
    },
  },
  Khordha: {
    district: "Khordha",
    year1: 2016,
    year2: 2024,
    scheme: "dynamic_world",
    num_hotspots: 5,
    total_transition_area_ha: 38181.24,
    new_built_total_ha: 207,
    settlement_type_breakdown_ha: {
      residential: 72,
      industrial: 92.52,
      mining_adjacent: 0,
      transport: 0,
      mixed: 42.48,
      unclassified: 0,
    },
    weights: {
      ndvi_delta: 0.15,
      ndbi_delta: 0.35,
      landcover_transition: 0.4,
      mndwi_delta: 0,
      nightlights_delta: 0.1,
    },
    hotspots: [
    {
      rank: 1,
      cord: [20.228, 85.7335],
      score: 902.5272,
      area_km2: 1,
      bounds_xyxy: [367200, 2236720, 368200, 2237720],
      dominant_from: "Crops",
      dominant_to: "Built",
      transition_area_ha: 58.68,
      new_built_area_ha: 72,
      from_class_breakdown: [{from_label: "Crops", area_ha: 58.68, pixel_count: 163}, {from_label: "Rangeland", area_ha: 13.32, pixel_count: 37}],
      settlement_type: "residential",
      settlement_rationale: "dominated by residential driver(s): Tamando (5.91 km), Jatni (7.34 km)",
      likely_cause: "Urban or industrial expansion onto farmland (likely driven by Tamando, ~5.91 km away)",
      confidence: 0.95,
      nearby_features: [{name: "Tamando", type: "urban_center", distance_km: 5.91, source: "district_context"}, {name: "Jatni", type: "urban_center", distance_km: 7.34, source: "district_context"}, {name: "Biju Patnaik International Airport", type: "airport", distance_km: 9.13, source: "district_context"}],
      narrative: "Hotspot 1 (20.2280°N, 85.7335°E), 2016→2024. New built-up area: 72.0 ha (58.68 ha from Crops, 13.32 ha from Rangeland). Why: nearest known feature is Tamando (urban center), ~5.91 km away. District drivers: urban expansion, IT / service-sector urbanisation, industrial. Likely cause: Urban or industrial expansion onto farmland (likely driven by Tamando, ~5.91 km away). Demographic signal: settlement / peri-urban growth (housing, population inflow) [dominated by residential driver(s): Tamando (5.91 km), Jatni (7.34 km)]. Confidence: 0.95.",
      chip: "outputs/Khordha/chips/hotspot_01.png",
      gif: "outputs/Khordha/gifs/hotspot_01.gif",
    },
    {
      rank: 2,
      cord: [20.3274, 85.7327],
      score: 779.7495,
      area_km2: 1,
      bounds_xyxy: [367200, 2247720, 368200, 2248720],
      dominant_from: "Rangeland",
      dominant_to: "Built",
      transition_area_ha: 52.2,
      new_built_area_ha: 56.88,
      from_class_breakdown: [{from_label: "Rangeland", area_ha: 52.2, pixel_count: 145}, {from_label: "Trees", area_ha: 3.96, pixel_count: 11}, {from_label: "Crops", area_ha: 0.72, pixel_count: 2}],
      settlement_type: "industrial",
      settlement_rationale: "dominated by industrial driver(s): Chandaka Industrial Estate (7.03 km), Infocity IT hub (9.44 km)",
      likely_cause: "Urban/industrial expansion onto rangeland (likely driven by Tamando, ~6.49 km away)",
      confidence: 0.9,
      nearby_features: [{name: "Tamando", type: "urban_center", distance_km: 6.49, source: "district_context"}, {name: "Chandaka Industrial Estate", type: "industrial", distance_km: 7.03, source: "district_context"}, {name: "Infocity IT hub", type: "industrial", distance_km: 9.44, source: "district_context"}],
      narrative: "Hotspot 2 (20.3274°N, 85.7327°E), 2016→2024. New built-up area: 56.88 ha (52.2 ha from Rangeland, 3.96 ha from Trees, 0.72 ha from Crops). Why: nearest known feature is Tamando (urban center), ~6.49 km away. District drivers: urban expansion, IT / service-sector urbanisation, industrial. Likely cause: Urban/industrial expansion onto rangeland (likely driven by Tamando, ~6.49 km away). Demographic signal: industrial build-out (plant expansion, workforce housing likely) [dominated by industrial driver(s): Chandaka Industrial Estate (7.03 km), Infocity IT hub (9.44 km)]. Confidence: 0.90.",
      chip: "outputs/Khordha/chips/hotspot_02.png",
      gif: "outputs/Khordha/gifs/hotspot_02.gif",
    },
    {
      rank: 3,
      cord: [20.2286, 85.8101],
      score: 658.6236,
      area_km2: 1,
      bounds_xyxy: [375200, 2236720, 376200, 2237720],
      dominant_from: "Crops",
      dominant_to: "Built",
      transition_area_ha: 42.12,
      new_built_area_ha: 42.48,
      from_class_breakdown: [{from_label: "Crops", area_ha: 42.12, pixel_count: 117}, {from_label: "Rangeland", area_ha: 0.36, pixel_count: 1}],
      settlement_type: "mixed",
      settlement_rationale: "industrial/residential/transport drivers overlap (Biju Patnaik International Airport (2.52 km); Tamando (7.34 km), Bhubaneswar (7.66 km))",
      likely_cause: "Urban or industrial expansion onto farmland (likely driven by Biju Patnaik International Airport, ~2.52 km away)",
      confidence: 0.95,
      nearby_features: [{name: "Biju Patnaik International Airport", type: "airport", distance_km: 2.52, source: "district_context"}, {name: "Bhubaneswar railway station", type: "railway_station", distance_km: 5.12, source: "district_context"}, {name: "Tamando", type: "urban_center", distance_km: 7.34, source: "district_context"}, {name: "Bhubaneswar", type: "urban_center", distance_km: 7.66, source: "district_context"}],
      narrative: "Hotspot 3 (20.2286°N, 85.8101°E), 2016→2024. New built-up area: 42.48 ha (42.12 ha from Crops, 0.36 ha from Rangeland). Why: nearest known feature is Biju Patnaik International Airport (airport), ~2.52 km away. District drivers: urban expansion, IT / service-sector urbanisation, industrial. Likely cause: Urban or industrial expansion onto farmland (likely driven by Biju Patnaik International Airport, ~2.52 km away). Demographic signal: mixed industrial + residential footprint [industrial/residential/transport drivers overlap (Biju Patnaik International Airport (2.52 km); Tamando (7.34 km), Bhubaneswar (7.66 km))]. Confidence: 0.95.",
      chip: "outputs/Khordha/chips/hotspot_03.png",
      gif: "outputs/Khordha/gifs/hotspot_03.gif",
    },
    {
      rank: 4,
      cord: [20.2024, 85.9634],
      score: 636.6965,
      area_km2: 1,
      bounds_xyxy: [391200, 2233720, 392200, 2234720],
      dominant_from: "Trees",
      dominant_to: "Built",
      transition_area_ha: 28.08,
      new_built_area_ha: 35.64,
      from_class_breakdown: [{from_label: "Trees", area_ha: 28.08, pixel_count: 78}, {from_label: "Crops", area_ha: 7.2, pixel_count: 20}, {from_label: "Rangeland", area_ha: 0.36, pixel_count: 1}],
      settlement_type: "industrial",
      settlement_rationale: "no registered driver nearby; Trees→Built transition in a forest-dominated district suggests frontier industrial/mining clearance",
      likely_cause: "Forest cleared for urban or industrial development",
      confidence: 0.75,
      nearby_features: [],
      narrative: "Hotspot 4 (20.2024°N, 85.9634°E), 2016→2024. New built-up area: 35.64 ha (28.08 ha from Trees, 7.2 ha from Crops, 0.36 ha from Rangeland). Why: no specific nearby feature registered; district drivers are urban expansion, IT / service-sector urbanisation, industrial. Likely cause: Forest cleared for urban or industrial development. Demographic signal: industrial build-out (plant expansion, workforce housing likely) [no registered driver nearby; Trees→Built transition in a forest-dominated district suggests frontier industrial/mining clearance]. Confidence: 0.75.",
      chip: "outputs/Khordha/chips/hotspot_04.png",
      gif: "outputs/Khordha/gifs/hotspot_04.gif",
    },
    {
      rank: 5,
      cord: [19.8882, 85.1059],
      score: 626.973,
      area_km2: 1,
      bounds_xyxy: [301200, 2199720, 302200, 2200720],
      dominant_from: "Trees",
      dominant_to: "Rangeland",
      transition_area_ha: 24.48,
      new_built_area_ha: 0,
      from_class_breakdown: [],
      settlement_type: "unclassified",
      settlement_rationale: "no nearby driver and no built-up transition",
      likely_cause: "Forest degradation to open rangeland",
      confidence: 0.6,
      nearby_features: [],
      narrative: "Hotspot 5 (19.8882°N, 85.1059°E), 2016→2024. No net new built-up inside hotspot; dominant change: Trees → Rangeland (24.5 ha). Why: no specific nearby feature registered; district drivers are urban expansion, IT / service-sector urbanisation, industrial. Likely cause: Forest degradation to open rangeland. Demographic signal: unclassified — needs ground-truth [no nearby driver and no built-up transition]. Confidence: 0.60.",
      chip: "outputs/Khordha/chips/hotspot_05.png",
      gif: "outputs/Khordha/gifs/hotspot_05.gif",
    },
    ],
    topTransitions: [
      { from_label: "Crops", to_label: "Rangeland", pixel_count: 19679, area_ha: 7084.44 },
      { from_label: "Crops", to_label: "Built", pixel_count: 16237, area_ha: 5845.32 },
      { from_label: "Trees", to_label: "Built", pixel_count: 9935, area_ha: 3576.6 },
      { from_label: "Rangeland", to_label: "Crops", pixel_count: 9387, area_ha: 3379.32 },
      { from_label: "Rangeland", to_label: "Trees", pixel_count: 8939, area_ha: 3218.04 },
      { from_label: "Trees", to_label: "Rangeland", pixel_count: 8529, area_ha: 3070.44 },
      { from_label: "Crops", to_label: "Trees", pixel_count: 6668, area_ha: 2400.48 },
      { from_label: "Trees", to_label: "Crops", pixel_count: 6012, area_ha: 2164.32 },
      { from_label: "Rangeland", to_label: "Built", pixel_count: 4525, area_ha: 1629 },
      { from_label: "Flooded vegetation", to_label: "Rangeland", pixel_count: 2172, area_ha: 781.92 },
    ],
    artifacts: {
      changeHeatmap: "outputs/Khordha/maps/change_heatmap.png",
      rgbBeforeAfter: "outputs/Khordha/maps/rgb_before_after.png",
      transitionMatrix: "outputs/Khordha/maps/transition_matrix.png",
      topTransitions: "outputs/Khordha/maps/top_transitions.png",
    },
  },
};

export const AVAILABLE_DISTRICTS = ["Angul", "Balangir", "Cuttack", "Kendujhar", "Khordha"] as const;
